
DECLARE 
	@StartDate	DATE,
	@EndDate	DATE,
	@NumMonths INT

SET @NumMonths = 12
SET @StartDate = DATEADD(m, -@NumMonths, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0))
SET @EndDate = DATEADD(m, 0, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0))

SELECT SignUpDate, 
	M1,
	CASE RowNum
		WHEN 1 THEN M2
		WHEN 2 THEN M3
		WHEN 3 THEN M4
		WHEN 4 THEN M5
		WHEN 5 THEN M6
		WHEN 6 THEN M7
		WHEN 7 THEN M8
		WHEN 8 THEN M9
		WHEN 9 THEN M10
		WHEN 10 THEN M11
		WHEN 11 THEN M12
		WHEN 12 THEN NULL
	END M2,
	CASE RowNum
		WHEN 1 THEN M3
		WHEN 2 THEN M4
		WHEN 3 THEN M5
		WHEN 4 THEN M6
		WHEN 5 THEN M7
		WHEN 6 THEN M8
		WHEN 7 THEN M9
		WHEN 8 THEN M10
		WHEN 9 THEN M11
		WHEN 10 THEN M12
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M3,
		CASE RowNum
		WHEN 1 THEN M4
		WHEN 2 THEN M5
		WHEN 3 THEN M6
		WHEN 4 THEN M7
		WHEN 5 THEN M8
		WHEN 6 THEN M9
		WHEN 7 THEN M10
		WHEN 8 THEN M11
		WHEN 9 THEN M12
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M4,
		CASE RowNum
		WHEN 1 THEN M5
		WHEN 2 THEN M6
		WHEN 3 THEN M7
		WHEN 4 THEN M8
		WHEN 5 THEN M9
		WHEN 6 THEN M10
		WHEN 7 THEN M11
		WHEN 8 THEN M12
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M5,
		CASE RowNum
		WHEN 1 THEN M6
		WHEN 2 THEN M7
		WHEN 3 THEN M8
		WHEN 4 THEN M9
		WHEN 5 THEN M10
		WHEN 6 THEN M11
		WHEN 7 THEN M12
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M6,
		CASE RowNum
		WHEN 1 THEN M7
		WHEN 2 THEN M8
		WHEN 3 THEN M9
		WHEN 4 THEN M10
		WHEN 5 THEN M11
		WHEN 6 THEN M12
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M7,
		CASE RowNum
		WHEN 1 THEN M8
		WHEN 2 THEN M9
		WHEN 3 THEN M10
		WHEN 4 THEN M11
		WHEN 5 THEN M12
		WHEN 6 THEN NULL
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M8,
		CASE RowNum
		WHEN 1 THEN M9
		WHEN 2 THEN M10
		WHEN 3 THEN M11
		WHEN 4 THEN M12
		WHEN 5 THEN NULL
		WHEN 6 THEN NULL
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M9,
		CASE RowNum
		WHEN 1 THEN M10
		WHEN 2 THEN M11
		WHEN 3 THEN M12
		WHEN 4 THEN NULL
		WHEN 5 THEN NULL
		WHEN 6 THEN NULL
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M10,
		CASE RowNum
		WHEN 1 THEN M11
		WHEN 2 THEN M12
		WHEN 3 THEN NULL
		WHEN 4 THEN NULL
		WHEN 5 THEN NULL
		WHEN 6 THEN NULL
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M11,
		CASE RowNum
		WHEN 1 THEN M12
		WHEN 2 THEN NULL
		WHEN 3 THEN NULL
		WHEN 4 THEN NULL
		WHEN 5 THEN NULL
		WHEN 6 THEN NULL
		WHEN 7 THEN NULL
		WHEN 8 THEN NULL
		WHEN 9 THEN NULL
		WHEN 10 THEN NULL
		WHEN 11 THEN NULL
		WHEN 12 THEN NULL
	END M12
FROM (
	SELECT ROW_NUMBER() OVER (ORDER BY SignUpDate) RowNum, SignUpDate,
		(TotalSignUp / TotalSignUp) * 1.0 M1,
		M2 / TotalSignUp M2,
		M3 / TotalSignUp M3,
		M4 / TotalSignUp M4,
		M5 / TotalSignUp M5,
		M6 / TotalSignUp M6,
		M7 / TotalSignUp M7,
		M8 / TotalSignUp M8,
		M9 / TotalSignUp M9,
		M10 / TotalSignUp M10,
		M11 / TotalSignUp M11,
		M12 / TotalSignUp M12
	FROM (
		SELECT SignUpDate, --1.0 M1,
			COUNT(DISTINCT ClientID) TotalSignUp,
			SUM(CASE WHEN MonthActive = DATEADD(m, 1, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M2,
			SUM(CASE WHEN MonthActive = DATEADD(m, 2, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M3,
			SUM(CASE WHEN MonthActive = DATEADD(m, 3, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M4,
			SUM(CASE WHEN MonthActive = DATEADD(m, 4, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M5,
			SUM(CASE WHEN MonthActive = DATEADD(m, 5, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M6,
			SUM(CASE WHEN MonthActive = DATEADD(m, 6, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M7,
			SUM(CASE WHEN MonthActive = DATEADD(m, 7, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M8,
			SUM(CASE WHEN MonthActive = DATEADD(m, 8, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M9,
			SUM(CASE WHEN MonthActive = DATEADD(m, 9, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M10,
			SUM(CASE WHEN MonthActive = DATEADD(m, 10, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M11,
			SUM(CASE WHEN MonthActive = DATEADD(m, 11, DATEADD(MONTH, DATEDIFF(MONTH, 0, @StartDate), 0)) THEN 1.0 ELSE 0.0 END) M12
		FROM (
			SELECT DISTINCT C.ClientID,DATEADD(m, 0, DATEADD(MONTH, DATEDIFF(MONTH, 0, SignUpDate), 0)) SignUpDate, DATEADD(m, 0, DATEADD(MONTH, DATEDIFF(MONTH, 0, TransactionDate), 0)) MonthActive
			FROM Client (nolock) C
			INNER JOIN ACTransaction (nolock) T ON C.ClientID = T.ClientID
			WHERE SignupDate BETWEEN @StartDate AND @EndDate
				AND TransactionDate BETWEEN @StartDate AND @EndDate
			) T
		GROUP BY SignUpDate
		) T
) T
ORDER BY 1
